theme: minima
title: My github page
author: Nianyang Chen
email: nianyangchen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is the final project for my AP CSP&CSA cource at East Brunswick HS. 

# social links
instagram_username: nianyangchen # DO NOT include the @ character, or else the build will fail!
github_username: nychub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
